development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: todo-app_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: todo-app_test
  pool: 5